"""empty message

Revision ID: 077329d50472
Revises: f2adeda3a8e2
Create Date: 2021-10-31 19:04:42.119819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077329d50472'
down_revision = 'f2adeda3a8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('request', sa.Column('longitude', sa.String(length=255), nullable=True))
    #op.add_column('request', sa.Column('latitude', sa.String(length=255), nullable=True))
    #op.drop_table('access')
    #op.create_foreign_key(None, 'request', 'endpoint', ['latitude'], ['latitude'])
    
    print("todo bien")
    #op.create_foreign_key(None, 'request', 'endpoint', ['longitude'], ['longitude'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'latitude')
    op.drop_column('request', 'longitude')
    # ### end Alembic commands ###
