"""empty message

Revision ID: 1193ff0bb3e6
Revises: 077329d50472
Create Date: 2021-10-31 19:24:02.669705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1193ff0bb3e6'
down_revision = '077329d50472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('longitude', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
