"""empty message

Revision ID: 1bbd5e160b5f
Revises: 009ebfe864c0
Create Date: 2021-11-08 13:17:32.032433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bbd5e160b5f'
down_revision = '009ebfe864c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("12")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filexreq', 'idFile',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
