"""empty message

Revision ID: 25c694255874
Revises: 1193ff0bb3e6
Create Date: 2021-10-31 19:24:32.713481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c694255874'
down_revision = '1193ff0bb3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('request', sa.Column('longitude', sa.String(length=255), nullable=True))
    #op.create_foreign_key(None, 'request', 'endpoint', ['longitude'], ['longitude'])
    print("todo bien")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'longitude')
    # ### end Alembic commands ###
