"""empty message

Revision ID: 269440eae444
Revises: 71ba81de6036
Create Date: 2021-11-05 03:36:44.009729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269440eae444'
down_revision = '71ba81de6036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('typeInput', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'typeInput')
    # ### end Alembic commands ###
