"""empty message

Revision ID: 276854dad38b
Revises: 
Create Date: 2021-10-30 22:59:24.772503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276854dad38b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint',
    sa.Column('ipClient', sa.String(length=15), nullable=False),
    sa.Column('latitude', sa.String(length=255), nullable=True),
    sa.Column('longitude', sa.String(length=255), nullable=True),
    sa.Column('countryName', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ipClient')
    )
    op.create_table('file',
    sa.Column('idFile', sa.Integer(), nullable=False),
    sa.Column('idSubGroup', sa.Integer(), nullable=True),
    sa.Column('haveStructure', sa.Boolean(), nullable=True),
    sa.Column('content', sa.BLOB(), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('isFragment', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idFile')
    )
    op.create_table('parameter',
    sa.Column('idParameter', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idParameter')
    )
    op.create_table('statusrequest',
    sa.Column('idStatus', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('idStatus')
    )
    op.create_table('typeinput',
    sa.Column('idTypeInput', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idTypeInput')
    )
    op.create_table('request',
    sa.Column('idRequest', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pfamID', sa.String(length=7), nullable=True),
    sa.Column('sequence', sa.BLOB(), nullable=True),
    sa.Column('isSequence', sa.Boolean(), nullable=True),
    sa.Column('idStatus', sa.Integer(), nullable=True),
    sa.Column('idTypeInput', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idStatus'], ['statusrequest.idStatus'], ),
    sa.ForeignKeyConstraint(['idTypeInput'], ['typeinput.idTypeInput'], ),
    sa.PrimaryKeyConstraint('idRequest')
    )
    op.create_table('access',
    sa.Column('dateAccess', sa.DateTime(), nullable=False),
    sa.Column('activityPut', sa.Boolean(), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('ipClient', sa.String(length=15), nullable=True),
    sa.Column('idRequest', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idRequest'], ['request.idRequest'], ),
    sa.ForeignKeyConstraint(['ipClient'], ['endpoint.ipClient'], ),
    sa.PrimaryKeyConstraint('dateAccess')
    )
    op.create_table('filexreq',
    sa.Column('isResult', sa.Boolean(), nullable=True),
    sa.Column('idRequest', sa.Integer(), nullable=False),
    sa.Column('idFile', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idFile'], ['file.idFile'], ),
    sa.ForeignKeyConstraint(['idRequest'], ['request.idRequest'], ),
    sa.PrimaryKeyConstraint('idRequest', 'idFile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filexreq')
    op.drop_table('access')
    op.drop_table('request')
    op.drop_table('typeinput')
    op.drop_table('statusrequest')
    op.drop_table('parameter')
    op.drop_table('file')
    op.drop_table('endpoint')
    # ### end Alembic commands ###
