"""empty message

Revision ID: 27e4edb85633
Revises: c50c97045721
Create Date: 2021-10-31 13:19:51.404080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e4edb85633'
down_revision = 'c50c97045721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access', sa.Column('idRequest', sa.String(length=8), nullable=True))
    op.create_foreign_key(None, 'access', 'request', ['idRequest'], ['idRequest'])
    op.add_column('filexreq', sa.Column('idRequest', sa.String(length=8), nullable=False))
    op.create_foreign_key(None, 'filexreq', 'request', ['idRequest'], ['idRequest'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filexreq', type_='foreignkey')
    op.drop_column('filexreq', 'idRequest')
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.drop_column('access', 'idRequest')
    # ### end Alembic commands ###
