"""empty message

Revision ID: 2b5aed8c4ce0
Revises: cd58f214fc2d
Create Date: 2021-10-31 20:49:29.366244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5aed8c4ce0'
down_revision = 'cd58f214fc2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('idEndpoint', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'endpoint', ['idEndpoint'], ['idEndpoint'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'idEndpoint')
    # ### end Alembic commands ###
