"""empty message

Revision ID: 2dbe77cc066a
Revises: e9815ef23af7
Create Date: 2021-10-31 20:09:59.782572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dbe77cc066a'
down_revision = 'e9815ef23af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('endpoint', sa.Column('idEndpoint', sa.Integer(), nullable=False))
    #op.alter_column('endpoint', 'latitude',existing_type=mysql.VARCHAR(length=255),nullable=True)
    #op.alter_column('endpoint', 'longitude', existing_type=mysql.VARCHAR(length=255),nullable=True)
    #op.add_column('request', sa.Column('ipClient', sa.String(length=15), nullable=True))
    #op.drop_constraint('request_ibfk_2', 'request', type_='foreignkey')
    op.drop_column('request', 'longitude')
    op.drop_column('request', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('latitude', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('request', sa.Column('longitude', mysql.VARCHAR(length=255), nullable=True))
    op.create_foreign_key('request_ibfk_2', 'request', 'endpoint', ['latitude', 'longitude'], ['latitude', 'longitude'])
    op.drop_column('request', 'ipClient')
    op.alter_column('endpoint', 'longitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('endpoint', 'latitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('endpoint', 'idEndpoint')
    # ### end Alembic commands ###
