"""empty message

Revision ID: 43891e1a20e0
Revises: 02bf8b0a98c0
Create Date: 2021-10-31 18:57:12.869151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43891e1a20e0'
down_revision = '02bf8b0a98c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endpoint', 'latitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('endpoint', 'longitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('endpoint', 'idEndpoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('idEndpoint', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('endpoint', 'longitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('endpoint', 'latitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
