"""empty message

Revision ID: 45a50fd73798
Revises: 2dbe77cc066a
Create Date: 2021-10-31 20:19:10.849018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a50fd73798'
down_revision = '2dbe77cc066a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('idEndpoint', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'endpoint', ['idEndpoint'], ['idEndpoint'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'idEndpoint')
    # ### end Alembic commands ###
