"""empty message

Revision ID: 53aa44cf6825
Revises: b8f4758e56cb
Create Date: 2021-10-31 18:11:00.295182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53aa44cf6825'
down_revision = 'b8f4758e56cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("todo bien")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access', sa.Column('idRequest', mysql.VARCHAR(length=8), nullable=True))
    op.add_column('access', sa.Column('latitude', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.create_foreign_key('access_ibfk_3', 'access', 'request', ['idRequest'], ['idRequest'])
    # ### end Alembic commands ###
