"""empty message

Revision ID: 62c43be9622e
Revises: b897da7918c1
Create Date: 2021-11-08 15:19:54.728608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62c43be9622e'
down_revision = 'b897da7918c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('filexreq_ibfk_1', 'filexreq', type_='foreignkey')
    op.drop_constraint('filexreq_ibfk_2', 'filexreq', type_='foreignkey')
    op.drop_column('filexreq', 'idRequest')
    op.drop_column('filexreq', 'idFile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filexreq', sa.Column('idFile', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('filexreq', sa.Column('idRequest', mysql.VARCHAR(length=8), nullable=True))
    op.create_foreign_key('filexreq_ibfk_2', 'filexreq', 'file', ['idFile'], ['idFile'])
    op.create_foreign_key('filexreq_ibfk_1', 'filexreq', 'request', ['idRequest'], ['idRequest'])
    # ### end Alembic commands ###
