"""empty message

Revision ID: 71ba81de6036
Revises: 351c1e729f57
Create Date: 2021-11-03 01:53:19.521292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ba81de6036'
down_revision = '351c1e729f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('dbAlgorithm', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'dbAlgorithm')
    # ### end Alembic commands ###
