"""empty message

Revision ID: 7cfbcece9d23
Revises: d4c78f65f4f0
Create Date: 2021-10-31 18:13:30.479006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfbcece9d23'
down_revision = 'd4c78f65f4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("todo bien")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.drop_column('access', 'latitude')
    op.drop_column('access', 'longitude')
    # ### end Alembic commands ###
