"""empty message

Revision ID: 98de92efc250
Revises: 276854dad38b
Create Date: 2021-10-31 13:09:00.049413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98de92efc250'
down_revision = '276854dad38b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
