"""empty message

Revision ID: aa3ed862b8b0
Revises: 269440eae444
Create Date: 2021-11-05 03:38:16.038642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3ed862b8b0'
down_revision = '269440eae444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('sequence', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
