"""empty message

Revision ID: abac71da3efb
Revises: 5657d6387976
Create Date: 2021-10-31 19:44:07.086275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abac71da3efb'
down_revision = '5657d6387976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('latitude', sa.String(length=255), nullable=True))
    op.add_column('request', sa.Column('longitude', sa.String(length=255), nullable=True))
    #op.create_foreign_key(None, 'request', 'endpoint', ['latitude'], ['latitude'])
    #op.create_foreign_key(None, 'request', 'endpoint', ['longitude'], ['longitude'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'longitude')
    op.drop_column('request', 'latitude')
    # ### end Alembic commands ###
