"""empty message

Revision ID: aef4c5852363
Revises: f013874f176d
Create Date: 2021-10-31 17:59:51.498010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aef4c5852363'
down_revision = 'f013874f176d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endpoint', 'ipClient',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('endpoint', 'latitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('endpoint', 'longitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endpoint', 'longitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('endpoint', 'latitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('endpoint', 'ipClient',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.drop_constraint(None, 'access', type_='foreignkey')
    # ### end Alembic commands ###
