"""empty message

Revision ID: af7bbd29c4fd
Revises: 27e4edb85633
Create Date: 2021-10-31 17:35:22.328819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af7bbd29c4fd'
down_revision = '27e4edb85633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    print("todo bien")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('idTypeInput', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('request_ibfk_2', 'request', 'typeinput', ['idTypeInput'], ['idTypeInput'])
    op.drop_column('request', 'totalTimeProcess')
    op.drop_column('endpoint', 'active')
    op.add_column('access', sa.Column('ipClient', mysql.VARCHAR(length=15), nullable=True))
    op.create_foreign_key('access_ibfk_2', 'access', 'endpoint', ['ipClient'], ['ipClient'])
    op.create_table('typeinput',
    sa.Column('idTypeInput', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idTypeInput'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
