"""empty message

Revision ID: b8f4758e56cb
Revises: aef4c5852363
Create Date: 2021-10-31 18:04:55.313284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f4758e56cb'
down_revision = 'aef4c5852363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("todo bien")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.drop_constraint(None, 'access', type_='foreignkey')
    # ### end Alembic commands ###
