"""empty message

Revision ID: c50c97045721
Revises: c0f6547b99d6
Create Date: 2021-10-31 13:17:49.990129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c50c97045721'
down_revision = 'c0f6547b99d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('filexreq_ibfk_2', 'filexreq', type_='foreignkey')
    op.drop_column('filexreq', 'idRequest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filexreq', sa.Column('idRequest', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('filexreq_ibfk_2', 'filexreq', 'request', ['idRequest'], ['idRequest'])
    # ### end Alembic commands ###
