"""empty message

Revision ID: c98195e5931b
Revises: 53aa44cf6825
Create Date: 2021-10-31 18:12:06.333979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98195e5931b'
down_revision = '53aa44cf6825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("todo  bien")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.drop_constraint(None, 'access', type_='foreignkey')
    # ### end Alembic commands ###
