"""empty message

Revision ID: cd58f214fc2d
Revises: 45a50fd73798
Create Date: 2021-10-31 20:48:35.392598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd58f214fc2d'
down_revision = '45a50fd73798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('request_ibfk_2', 'request', type_='foreignkey')
    op.drop_column('request', 'idEndpoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('idEndpoint', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('request_ibfk_2', 'request', 'endpoint', ['idEndpoint'], ['idEndpoint'])
    # ### end Alembic commands ###
