"""empty message

Revision ID: d8dfae91ce18
Revises: 62c43be9622e
Create Date: 2021-11-08 15:26:01.341545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dfae91ce18'
down_revision = '62c43be9622e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filexreq',
    sa.Column('idFilexreq', sa.Integer(), nullable=False),
    sa.Column('isResult', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idFilexreq')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filexreq')
    # ### end Alembic commands ###
