"""empty message

Revision ID: e8f563f8cadb
Revises: 7cfbcece9d23
Create Date: 2021-10-31 18:21:39.102366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8f563f8cadb'
down_revision = '7cfbcece9d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access', 'longitude')
    op.drop_column('access', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access', sa.Column('latitude', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('access', sa.Column('longitude', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
