"""empty message

Revision ID: e9815ef23af7
Revises: abac71da3efb
Create Date: 2021-10-31 19:52:20.323726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9815ef23af7'
down_revision = 'abac71da3efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('request_ibfk_2', 'request', type_='foreignkey')
    #op.create_foreign_key(None, 'request', 'endpoint', ['longitude'], ['longitude'])
    #op.create_foreign_key(None, 'request', 'endpoint', ['latitude'], ['latitude'])
    # ### end Alembic commands ###
    print("todo bien")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.create_foreign_key('request_ibfk_2', 'request', 'endpoint', ['latitude', 'longitude'], ['latitude', 'longitude'])
    # ### end Alembic commands ###
