"""empty message

Revision ID: f013874f176d
Revises: af7bbd29c4fd
Create Date: 2021-10-31 17:55:31.072793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f013874f176d'
down_revision = 'af7bbd29c4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    print("todo bien")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endpoint', 'longitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('endpoint', 'latitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('endpoint', 'ipClient',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.drop_column('access', 'latitude')
    op.drop_column('access', 'longitude')
    # ### end Alembic commands ###
