"""empty message

Revision ID: f2adeda3a8e2
Revises: 43891e1a20e0
Create Date: 2021-10-31 19:03:09.100775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2adeda3a8e2'
down_revision = '43891e1a20e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('access_ibfk_3', 'access', type_='foreignkey')
    op.drop_column('access', 'activityPut')
    op.drop_column('access', 'browser')
    op.drop_column('access', 'idRequest')
    op.add_column('request', sa.Column('browser', sa.String(length=255), nullable=True))
    op.add_column('request', sa.Column('dateAccess', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'dateAccess')
    op.drop_column('request', 'browser')
    op.add_column('access', sa.Column('idRequest', mysql.VARCHAR(length=8), nullable=True))
    op.add_column('access', sa.Column('browser', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('access', sa.Column('activityPut', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_foreign_key('access_ibfk_3', 'access', 'request', ['idRequest'], ['idRequest'])
    # ### end Alembic commands ###
