"""empty message

Revision ID: f3b27870fd9f
Revises: 5654e60a2574
Create Date: 2021-11-08 20:05:40.547128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b27870fd9f'
down_revision = '5654e60a2574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('tmscore', sa.Numeric(precision=4, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'tmscore')
    # ### end Alembic commands ###
