"""empty message

Revision ID: f67382334567
Revises: 98de92efc250
Create Date: 2021-10-31 13:10:40.802628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67382334567'
down_revision = '98de92efc250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'email')
    # ### end Alembic commands ###
