"""empty message

Revision ID: fb0e522ea38f
Revises: 
Create Date: 2022-01-27 16:44:38.281313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0e522ea38f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint',
    sa.Column('idEndpoint', sa.Integer(), nullable=False),
    sa.Column('countryName', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=255), nullable=True),
    sa.Column('longitude', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idEndpoint')
    )
    op.create_table('file',
    sa.Column('idFile', sa.Integer(), nullable=False),
    sa.Column('idSubGroup', sa.Integer(), nullable=True),
    sa.Column('haveStructure', sa.Boolean(), nullable=True),
    sa.Column('nameFile', sa.String(length=255), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('isFragment', sa.Boolean(), nullable=True),
    sa.Column('dbAlgorithm', sa.String(length=25), nullable=True),
    sa.Column('tmscore', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('idFile')
    )
    op.create_table('parameter',
    sa.Column('idParameter', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idParameter')
    )
    op.create_table('statusrequest',
    sa.Column('idStatus', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('idStatus')
    )
    op.create_table('access',
    sa.Column('idAccess', sa.Integer(), nullable=False),
    sa.Column('ipClient', sa.String(length=15), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('idEndpoint', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEndpoint'], ['endpoint.idEndpoint'], ),
    sa.PrimaryKeyConstraint('idAccess')
    )
    op.create_table('request',
    sa.Column('idRequest', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pfamID', sa.String(length=7), nullable=True),
    sa.Column('typeInput', sa.String(length=30), nullable=True),
    sa.Column('totalTimeProcess', sa.Integer(), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('dateAccess', sa.DateTime(), nullable=True),
    sa.Column('idStatus', sa.Integer(), nullable=True),
    sa.Column('idAccess', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAccess'], ['access.idAccess'], ),
    sa.ForeignKeyConstraint(['idStatus'], ['statusrequest.idStatus'], ),
    sa.PrimaryKeyConstraint('idRequest')
    )
    op.create_table('filexreq',
    sa.Column('idFilexreq', sa.Integer(), nullable=False),
    sa.Column('isResult', sa.Boolean(), nullable=True),
    sa.Column('idRequest', sa.String(length=8), nullable=True),
    sa.Column('idFile', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idFile'], ['file.idFile'], ),
    sa.ForeignKeyConstraint(['idRequest'], ['request.idRequest'], ),
    sa.PrimaryKeyConstraint('idFilexreq')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filexreq')
    op.drop_table('request')
    op.drop_table('access')
    op.drop_table('statusrequest')
    op.drop_table('parameter')
    op.drop_table('file')
    op.drop_table('endpoint')
    # ### end Alembic commands ###
